<html>
<head>
    <title>Resumes</title>
</head>
<body>
<table border="1">
    <tr>
        <td>resume1</td>
        <td>resume1</td>
    </tr>
    <tr>
        <td>resume1</td>
        <td>resume1</td>
    </tr>
    <tr>
        <td>resume1</td>
        <td>resume1</td>
    </tr>
</table>
</body>
</html>